use_frameworks!

platform :ios, '13.0'

target 'MMTToolForAppTrans_Example' do
  pod 'MMTToolForAppTrans', :path => '../'

  target 'MMTToolForAppTrans_Tests' do
    inherit! :search_paths

#    pod 'Quick'
#    pod 'Nimble'
#    pod 'FBSnapshotTestCase'
#    pod 'Nimble-Snapshots'
  end
end
